// packages/vue/src/AparsoftChatbot.vue
<template>
  <span aria-hidden="true" style="display: none"></span>
</template>

<script>
const WIDGET_SCRIPT_URL = 'https://www.aparsoft.com/static/chatbot-widget/widget.loader.js';
const READY_EVENT = 'aparsoft-chatbot:ready';
const DEFAULT_CONFIG_ENDPOINT =
  'https://www.aparsoft.com/api/v1/chatbot/public/widget/{apiKey}/config/';
const DEFAULT_WEBSOCKET_URL = 'wss://www.aparsoft.com/ws/client-chatbot/';

function applyLoaderDataset(script, config) {
  script.dataset.aparsoftChatbot = 'true';
  script.dataset.apiKey = config.apiKey;

  if (config.position) script.dataset.position = config.position;
  if (typeof config.showBranding === 'boolean')
    script.dataset.showBranding = String(config.showBranding);
  if (config.autoOpenDelayMs > 0) script.dataset.autoOpenDelayMs = String(config.autoOpenDelayMs);
  if (config.configEndpoint) script.dataset.configEndpoint = config.configEndpoint;
  if (config.websocketUrl) script.dataset.websocketUrl = config.websocketUrl;
  if (config.primaryColor) script.dataset.primaryColor = config.primaryColor;
  if (config.secondaryColor) script.dataset.secondaryColor = config.secondaryColor;
  if (config.widgetTitle) script.dataset.widgetTitle = config.widgetTitle;
  if (config.widgetSubtitle) script.dataset.widgetSubtitle = config.widgetSubtitle;
  if (config.welcomeMessage) script.dataset.welcomeMessage = config.welcomeMessage;
  if (config.title) script.dataset.title = config.title;
}

export default {
  name: 'AparsoftChatbot',

  props: {
    apiKey: {
      type: String,
      required: true,
    },
    position: {
      type: String,
      default: 'bottom-right',
    },
    showBranding: {
      type: Boolean,
      default: true,
    },
    autoOpenDelay: {
      type: Number,
      default: 0,
    },
    configEndpoint: {
      type: String,
      default: DEFAULT_CONFIG_ENDPOINT,
    },
    websocketUrl: {
      type: String,
      default: DEFAULT_WEBSOCKET_URL,
    },
    primaryColor: {
      type: String,
      default: null,
    },
    secondaryColor: {
      type: String,
      default: null,
    },
    widgetTitle: {
      type: String,
      default: null,
    },
    widgetSubtitle: {
      type: String,
      default: null,
    },
    welcomeMessage: {
      type: String,
      default: null,
    },
    title: {
      type: String,
      default: 'Aparsoft chat widget',
    },
  },

  data() {
    return {
      handleReady: null,
      loaderScript: null,
    };
  },

  mounted() {
    this.bootstrap();
  },

  beforeUnmount() {
    this.destroyWidget();
  },

  beforeDestroy() {
    this.destroyWidget();
  },

  watch: {
    apiKey: 'bootstrap',
    position: 'bootstrap',
    showBranding: 'bootstrap',
    autoOpenDelay: 'bootstrap',
    configEndpoint: 'bootstrap',
    websocketUrl: 'bootstrap',
    primaryColor: 'bootstrap',
    secondaryColor: 'bootstrap',
    widgetTitle: 'bootstrap',
    widgetSubtitle: 'bootstrap',
    welcomeMessage: 'bootstrap',
    title: 'bootstrap',
  },

  methods: {
    bootstrap() {
      if (typeof window === 'undefined' || typeof document === 'undefined' || !this.apiKey) {
        return;
      }

      this.destroyWidget();

      const config = {
        apiKey: this.apiKey,
        position: this.position,
        showBranding: this.showBranding,
        autoOpenDelayMs: this.autoOpenDelay,
        configEndpoint: this.configEndpoint,
        websocketUrl: this.websocketUrl,
        primaryColor: this.primaryColor,
        secondaryColor: this.secondaryColor,
        widgetTitle: this.widgetTitle,
        widgetSubtitle: this.widgetSubtitle,
        welcomeMessage: this.welcomeMessage,
        title: this.title,
      };

      this.handleReady = (event) => {
        const controller =
          (event && event.detail ? event.detail.controller : null) ||
          window.AparsoftChatbot ||
          null;
        if (controller) {
          this.$emit('ready', controller);
        }
      };

      window.addEventListener(READY_EVENT, this.handleReady);

      const existingScript = document.querySelector(
        'script[src="' + WIDGET_SCRIPT_URL + '"][data-aparsoft-chatbot]',
      );
      if (existingScript) {
        existingScript.remove();
      }

      if (window.AparsoftChatbot && typeof window.AparsoftChatbot.destroy === 'function') {
        window.AparsoftChatbot.destroy();
      }
      window.AparsoftChatbot = null;

      this.loaderScript = document.createElement('script');
      this.loaderScript.src = WIDGET_SCRIPT_URL;
      this.loaderScript.async = true;
      applyLoaderDataset(this.loaderScript, config);
      document.body.appendChild(this.loaderScript);

      if (window.AparsoftChatbot && window.AparsoftChatbot.isReady) {
        this.handleReady({ detail: { controller: window.AparsoftChatbot } });
      }
    },

    destroyWidget() {
      if (typeof window === 'undefined') {
        return;
      }

      if (this.handleReady) {
        window.removeEventListener(READY_EVENT, this.handleReady);
        this.handleReady = null;
      }

      if (this.loaderScript) {
        this.loaderScript.remove();
        this.loaderScript = null;
      }

      if (window.AparsoftChatbot && typeof window.AparsoftChatbot.destroy === 'function') {
        window.AparsoftChatbot.destroy();
        window.AparsoftChatbot = null;
      }
    },
  },
};
</script>

// packages/angular/src/aparsoft-chatbot.component.ts
import {
  Component,
  EventEmitter,
  Inject,
  Input,
  OnDestroy,
  OnInit,
  Output,
  PLATFORM_ID,
} from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

type WidgetPosition = 'bottom-right' | 'bottom-left';

export interface AparsoftChatbotConfig {
  apiKey: string;
  position?: WidgetPosition;
  showBranding?: boolean;
  autoOpenDelayMs?: number;
  configEndpoint?: string;
  websocketUrl?: string;
  primaryColor?: string | null;
  secondaryColor?: string | null;
  widgetTitle?: string | null;
  widgetSubtitle?: string | null;
  welcomeMessage?: string | null;
  title?: string | null;
}

export interface AparsoftChatbotInstance {
  isReady?: boolean;
  state?: string;
  open?: () => void;
  close?: () => void;
  toggle?: () => void;
  sendMessage?: (message: string) => void;
  destroy?: () => void;
}

const WIDGET_SCRIPT_URL = 'https://www.aparsoft.com/static/chatbot-widget/widget.loader.js';
const READY_EVENT = 'aparsoft-chatbot:ready';
const DEFAULT_CONFIG_ENDPOINT =
  'https://www.aparsoft.com/api/v1/chatbot/public/widget/{apiKey}/config/';
const DEFAULT_WEBSOCKET_URL = 'wss://www.aparsoft.com/ws/client-chatbot/';

@Component({
  selector: 'aparsoft-chatbot',
  template: '',
  standalone: true,
})
export class AparsoftChatbotComponent implements OnInit, OnDestroy {
  @Input() apiKey = '';
  @Input() position: WidgetPosition = 'bottom-right';
  @Input() showBranding = true;
  @Input() autoOpenDelay = 0;
  @Input() configEndpoint = DEFAULT_CONFIG_ENDPOINT;
  @Input() websocketUrl = DEFAULT_WEBSOCKET_URL;
  @Input() primaryColor: string | null = null;
  @Input() secondaryColor: string | null = null;
  @Input() widgetTitle: string | null = null;
  @Input() widgetSubtitle: string | null = null;
  @Input() welcomeMessage: string | null = null;
  @Input() title: string | null = 'Aparsoft chat widget';

  @Output() ready = new EventEmitter<AparsoftChatbotInstance>();
  @Output() error = new EventEmitter<Error>();

  private loaderScript: HTMLScriptElement | null = null;
  private handleReady: ((event: Event) => void) | null = null;

  constructor(@Inject(PLATFORM_ID) private platformId: object) {}

  ngOnInit(): void {
    this.bootstrap();
  }

  ngOnDestroy(): void {
    this.destroyWidget();
  }

  private bootstrap(): void {
    if (!isPlatformBrowser(this.platformId) || !this.apiKey) {
      return;
    }

    this.destroyWidget();

    const config: AparsoftChatbotConfig = {
      apiKey: this.apiKey,
      position: this.position,
      showBranding: this.showBranding,
      autoOpenDelayMs: this.autoOpenDelay,
      configEndpoint: this.configEndpoint,
      websocketUrl: this.websocketUrl,
      primaryColor: this.primaryColor,
      secondaryColor: this.secondaryColor,
      widgetTitle: this.widgetTitle,
      widgetSubtitle: this.widgetSubtitle,
      welcomeMessage: this.welcomeMessage,
      title: this.title,
    };

    this.handleReady = (event: Event) => {
      const controller =
        (event as CustomEvent).detail?.controller || window.AparsoftChatbot || null;
      if (controller) {
        this.ready.emit(controller);
      }
    };

    window.addEventListener(READY_EVENT, this.handleReady);

    const existingScript = document.querySelector(
      'script[src="' + WIDGET_SCRIPT_URL + '"][data-aparsoft-chatbot]',
    ) as HTMLScriptElement | null;
    if (existingScript) {
      existingScript.remove();
    }

    window.AparsoftChatbot?.destroy?.();
    window.AparsoftChatbot = null;

    this.loaderScript = document.createElement('script');
    this.loaderScript.src = WIDGET_SCRIPT_URL;
    this.loaderScript.async = true;
    this.loaderScript.dataset.aparsoftChatbot = 'true';
    this.loaderScript.dataset.apiKey = config.apiKey;
    if (config.position) this.loaderScript.dataset.position = config.position;
    if (typeof config.showBranding === 'boolean')
      this.loaderScript.dataset.showBranding = String(config.showBranding);
    if (config.autoOpenDelayMs && config.autoOpenDelayMs > 0)
      this.loaderScript.dataset.autoOpenDelayMs = String(config.autoOpenDelayMs);
    if (config.configEndpoint) this.loaderScript.dataset.configEndpoint = config.configEndpoint;
    if (config.websocketUrl) this.loaderScript.dataset.websocketUrl = config.websocketUrl;
    if (config.primaryColor) this.loaderScript.dataset.primaryColor = config.primaryColor;
    if (config.secondaryColor) this.loaderScript.dataset.secondaryColor = config.secondaryColor;
    if (config.widgetTitle) this.loaderScript.dataset.widgetTitle = config.widgetTitle;
    if (config.widgetSubtitle) this.loaderScript.dataset.widgetSubtitle = config.widgetSubtitle;
    if (config.welcomeMessage) this.loaderScript.dataset.welcomeMessage = config.welcomeMessage;
    if (config.title) this.loaderScript.dataset.title = config.title;
    document.body.appendChild(this.loaderScript);
  }

  private destroyWidget(): void {
    if (!isPlatformBrowser(this.platformId)) {
      return;
    }

    if (this.handleReady) {
      window.removeEventListener(READY_EVENT, this.handleReady);
      this.handleReady = null;
    }

    this.loaderScript?.remove();
    this.loaderScript = null;

    window.AparsoftChatbot?.destroy?.();
    window.AparsoftChatbot = null;
  }
}
